import com.sun.glass.events.KeyEvent;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
public class Patient extends javax.swing.JFrame {

private Connection con =null;
    private JTable RequestBloodTable;
    public Patient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        ProfileDTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        SearchTable = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CityRequestCombo1 = new javax.swing.JComboBox();
        SearchCityButton = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        SearchBloodButton = new javax.swing.JButton();
        CityRequestCombo2 = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        SearchDateButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        CityRequestCombo3 = new javax.swing.JComboBox();
        jPanel9 = new javax.swing.JPanel();
        SearchBankButton = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        CityRequestCombo4 = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AvailBloodDonorTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CityRequestCombo = new javax.swing.JComboBox();
        IdRequesttxt = new javax.swing.JTextField();
        RequestDateChooser = new com.toedter.calendar.JDateChooser();
        NameRequesttxt = new javax.swing.JTextField();
        BankRequesttxt = new javax.swing.JTextField();
        LocationRequesttxt = new javax.swing.JTextField();
        BTypeRequestCombo = new javax.swing.JComboBox();
        BottleRequestCombo = new javax.swing.JComboBox();
        RUpdateButton = new javax.swing.JButton();
        RDeleteButton = new javax.swing.JButton();
        RInsertButton = new javax.swing.JButton();
        LogoutDButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 102), 4, true), "DONATE BLOOD AND BE A HERO!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MingLiU", 1, 24), new java.awt.Color(255, 102, 0))); // NOI18N

        jTabbedPane1.setBackground(new java.awt.Color(0, 102, 0));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MingLiU", 1, 18), new java.awt.Color(255, 153, 0))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 51), 4, true), "All Blood Requests Come From All Over The World Help Save A Life Today Thank You And Stay Safe.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 153, 0))); // NOI18N

        ProfileDTable.setBackground(new java.awt.Color(0, 102, 102));
        jScrollPane3.setViewportView(ProfileDTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 982, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 55, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Profile", jPanel2);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 51), 4, true), " Search Blood ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("MingLiU", 1, 18), new java.awt.Color(255, 153, 0))); // NOI18N

        SearchTable.setBackground(new java.awt.Color(0, 102, 102));
        SearchTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SearchTableMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(SearchTable);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));

        jLabel13.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel13.setText("City/Town");

        SearchCityButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SearchCityButton.setText("Search");
        SearchCityButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchCityButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(SearchCityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(CityRequestCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel13)
                .addGap(60, 60, 60)
                .addComponent(CityRequestCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(SearchCityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(235, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab(" City/Town", jPanel6);

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));

        jLabel14.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel14.setText("Blood Type");

        SearchBloodButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SearchBloodButton.setText("Search");
        SearchBloodButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBloodButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(CityRequestCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(SearchBloodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jLabel14)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel14)
                .addGap(55, 55, 55)
                .addComponent(CityRequestCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(SearchBloodButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Blood Type", jPanel7);

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));

        SearchDateButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SearchDateButton.setText("Search");
        SearchDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDateButtonActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel15.setText("Date");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(SearchDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(44, 44, 44))
                    .addComponent(CityRequestCombo3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel15)
                .addGap(42, 42, 42)
                .addComponent(CityRequestCombo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(SearchDateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab(" Date", jPanel8);

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));

        SearchBankButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        SearchBankButton.setText("Search");
        SearchBankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBankButtonActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel16.setText("Bank Name");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(158, 158, 158))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(SearchBankButton, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(CityRequestCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel16)
                .addGap(42, 42, 42)
                .addComponent(CityRequestCombo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(SearchBankButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(268, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab(" Bank Name", jPanel9);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 593, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jTabbedPane1.addTab("Search Specific Record", jPanel5);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 102), 4, true), "PLACE YOUR REQUEST", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 18), new java.awt.Color(255, 102, 0))); // NOI18N

        AvailBloodDonorTable.setBackground(new java.awt.Color(0, 102, 102));
        AvailBloodDonorTable.setForeground(new java.awt.Color(255, 204, 0));
        AvailBloodDonorTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AvailBloodDonorTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(AvailBloodDonorTable);

        jLabel2.setBackground(new java.awt.Color(0, 102, 51));
        jLabel2.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 0));
        jLabel2.setText("User Id");

        jLabel4.setBackground(new java.awt.Color(0, 102, 51));
        jLabel4.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 153, 0));
        jLabel4.setText("User Name");

        jLabel5.setBackground(new java.awt.Color(0, 102, 51));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 0));
        jLabel5.setText("Blood Bank Name");

        jLabel6.setBackground(new java.awt.Color(0, 102, 51));
        jLabel6.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 153, 0));
        jLabel6.setText("City/Town");

        jLabel7.setBackground(new java.awt.Color(0, 102, 51));
        jLabel7.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 153, 0));
        jLabel7.setText("Blood Type");

        jLabel8.setBackground(new java.awt.Color(0, 102, 51));
        jLabel8.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("Location");

        jLabel9.setBackground(new java.awt.Color(0, 102, 51));
        jLabel9.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 153, 0));
        jLabel9.setText("Units");

        jLabel10.setBackground(new java.awt.Color(0, 102, 51));
        jLabel10.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 153, 0));
        jLabel10.setText("Date");

        CityRequestCombo.setBackground(new java.awt.Color(0, 102, 51));
        CityRequestCombo.setForeground(new java.awt.Color(255, 153, 0));
        CityRequestCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alice", "Butterworth", "Bethlehem", "Bloemfontein", "East London", "Graaff-Reinet", "Grahamstown", "Jagersfontein", "King William’s Town", "Mthatha", "Port Elizabeth", "Queenstown", "Uitenhage", "Zwelitsha" }));

        IdRequesttxt.setEditable(false);
        IdRequesttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                IdRequesttxtKeyPressed(evt);
            }
        });

        RequestDateChooser.setBackground(new java.awt.Color(0, 102, 51));
        RequestDateChooser.setForeground(new java.awt.Color(255, 153, 0));

        NameRequesttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NameRequesttxtKeyPressed(evt);
            }
        });

        LocationRequesttxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LocationRequesttxtKeyPressed(evt);
            }
        });

        BTypeRequestCombo.setBackground(new java.awt.Color(0, 102, 51));
        BTypeRequestCombo.setForeground(new java.awt.Color(255, 153, 0));
        BTypeRequestCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O+", "O-", "A+", "A-", "B+", "B-", "AB+", "AB-" }));

        BottleRequestCombo.setBackground(new java.awt.Color(0, 102, 51));
        BottleRequestCombo.setForeground(new java.awt.Color(255, 153, 0));
        BottleRequestCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", " " }));

        RUpdateButton.setBackground(new java.awt.Color(0, 102, 51));
        RUpdateButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RUpdateButton.setForeground(new java.awt.Color(255, 153, 0));
        RUpdateButton.setText("Update");
        RUpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUpdateButtonActionPerformed(evt);
            }
        });

        RDeleteButton.setBackground(new java.awt.Color(0, 102, 51));
        RDeleteButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RDeleteButton.setForeground(new java.awt.Color(255, 153, 0));
        RDeleteButton.setText("Delete");
        RDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RDeleteButtonActionPerformed(evt);
            }
        });

        RInsertButton.setBackground(new java.awt.Color(0, 102, 51));
        RInsertButton.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RInsertButton.setForeground(new java.awt.Color(255, 153, 0));
        RInsertButton.setText("Insert");
        RInsertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RInsertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel10)
                        .addComponent(jLabel9)))
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameRequesttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(BTypeRequestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CityRequestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BottleRequestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BankRequesttxt)
                        .addComponent(LocationRequesttxt)
                        .addComponent(RequestDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(IdRequesttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(RInsertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(IdRequesttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(NameRequesttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(BankRequesttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(CityRequestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(BTypeRequestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(LocationRequesttxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(BottleRequestCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(RequestDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(RUpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51)
                        .addComponent(RDeleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(RInsertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80))
        );

        jTabbedPane1.addTab("Request", jPanel3);

        LogoutDButton.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        LogoutDButton.setText("Logout");
        LogoutDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutDButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(LogoutDButton))
            .addComponent(jTabbedPane1)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(LogoutDButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AvailBloodDonorTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AvailBloodDonorTableMouseClicked
        int row = AvailBloodDonorTable.getSelectedRow();
        int value = Integer.parseInt(AvailBloodDonorTable.getModel().getValueAt(row, 0).toString());

        con = DBSCon.dataBaseConnection();
        try
        {
            Statement st = con.createStatement();
            String queery = "select * from Request where id = '"+value+"'";
            ResultSet rs = st.executeQuery(queery);

            if (rs.next())
            {

                IdRequesttxt.setText(rs.getString(1));
                NameRequesttxt.setText(rs.getString(2));
                BankRequesttxt.setText(rs.getString(3));
                CityRequestCombo.setSelectedItem(rs.getString(4));
                BTypeRequestCombo.setSelectedItem(rs.getString(5));
                LocationRequesttxt.setText(rs.getString(6));
                BottleRequestCombo.setSelectedItem(rs.getString(7));
                Date date = rs.getDate(8);
                RequestDateChooser.setDate(date);

            }
        }catch(Exception ex)
        {

        }
        finally
        {
            try
            {
                con.close();
            }catch(Exception ex)
            {

            }
        }

    }//GEN-LAST:event_AvailBloodDonorTableMouseClicked

    private void RUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUpdateButtonActionPerformed
        con = DBSCon.dataBaseConnection();
        String date = ((JTextField)RequestDateChooser.getDateEditor().getUiComponent()).getText();
        try
        {
            Statement st = con.createStatement();
            String queery = "update Request set Name = '"+NameRequesttxt.getText()+"', BloodBank = '"+BankRequesttxt.getText()+"', BloodType = '"+BTypeRequestCombo.getSelectedItem()+"',Location = '"+LocationRequesttxt.getText()+"', Bottles = '"+BottleRequestCombo.getSelectedItem()+"',Date = '"+date+"' where Id = '"+Integer.parseInt(IdRequesttxt.getText())+"' and City = '"+CityRequestCombo.getSelectedItem()+"' ";
            st.executeUpdate(queery);
            JOptionPane.showMessageDialog(null, "Data Updated ");
            showSpecificBloodData(Integer.parseInt(MainForm.getID()));
        }catch(Exception ex)
        {

        }
        finally
        {
            try
            {
                con.close();
            }catch(Exception ex)
            {

            }
        }
    }//GEN-LAST:event_RUpdateButtonActionPerformed

    private void RDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RDeleteButtonActionPerformed
        con = DBSCon.dataBaseConnection();
        try
        {
            Statement st = con.createStatement();
            String queery = "delete from Request where Id = '"+IdRequesttxt.getText()+"' and Name = '"+NameRequesttxt.getText()+"' ";
            st.executeUpdate(queery);
            JOptionPane.showMessageDialog(null, "Data Deleted ");
            showSpecificBloodData(Integer.parseInt(MainForm.getID()));
        }catch(Exception ex)
        {

        }
        finally
        {
            try
            {
                con.close();
            }catch(Exception ex)
            {

            }
        }
    }//GEN-LAST:event_RDeleteButtonActionPerformed

    private void RInsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RInsertButtonActionPerformed
        String date = ((JTextField)RequestDateChooser.getDateEditor().getUiComponent()).getText();
        con = DBSCon.dataBaseConnection();
        try
        {

            Statement st = con.createStatement();
            String queery = "insert into Request values ('"+Integer.parseInt(IdRequesttxt.getText())+"','"+NameRequesttxt.getText()+"','"+BankRequesttxt.getText()+"','"+CityRequestCombo.getSelectedItem()+"','"+BTypeRequestCombo.getSelectedItem()+"','"+LocationRequesttxt.getText()+"','"+BottleRequestCombo.getSelectedItem()+"','"+date+"')";
            st.executeUpdate(queery);
            JOptionPane.showMessageDialog(null," Data Inserted Sucessfully");
            showSpecificBloodData(Integer.parseInt(MainForm.getID()));
        }catch(Exception ex)
        {

        }
        finally
        {
            try
            {
                con.close();
            }catch(Exception ex)
            {

            }
        }

    }//GEN-LAST:event_RInsertButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        IdRequesttxt.setText(MainForm.getID());
      //  GenrelClass.showDataIntoTable("Avail_Blood", AvailableBloodTable);
        showProfile();
     //   
        showSpecificBloodData(Integer.parseInt(MainForm.getID()));
       getCityComboBox();
       getDateComboBox();
       getlBloodTypeComboBox();
       getBankComboBox();
    }//GEN-LAST:event_formWindowActivated

    
    public void getBankComboBox()
    {
        
            con = DBSCon.dataBaseConnection();
        
        try
        {
            Statement st = con.createStatement();
            String queery = "select distinct BloodBank from Avail_Blood";
            
                ResultSet rs = st.executeQuery(queery);
                while(rs.next())
                {
                    CityRequestCombo4.addItem(rs.getString("BloodBank"));
                }
            
        }catch(Exception ex)
        {

        }
        finally
        {
            try
            {
                con.close();
            }catch(Exception ex)
            {

            }
        }
         
    }
    
    public void getDateComboBox()
    {
        
            con = DBSCon.dataBaseConnection();
        
        try
        {
            Statement st = con.createStatement();
            String queery = "select distinct Date from Avail_Blood";
            
                ResultSet rs = st.executeQuery(queery);
                while(rs.next())
                {
                    CityRequestCombo3.addItem(rs.getString("Date"));
                }
            
        }catch(Exception ex)
        {

        }
        finally
        {
            try
            {
                con.close();
            }catch(Exception ex)
            {

            }
        }
         
    }
    
   public void getlBloodTypeComboBox()
    {
        
            con = DBSCon.dataBaseConnection();
        
        try
        {
            Statement st = con.createStatement();
            String queery = "select distinct BloodType from Avail_Blood";
            
                ResultSet rs = st.executeQuery(queery);
                while(rs.next())
                {
                    CityRequestCombo2.addItem(rs.getString("BloodType"));
                }
            
        }catch(Exception ex)
        {

        }
        finally
        {
            try
            {
                con.close();
            }catch(Exception ex)
            {

            }
        }
         
    }
    
    
    public void getCityComboBox()
    {
        
            con = DBSCon.dataBaseConnection();
        
        try
        {
            Statement st = con.createStatement();
            String queery = "select distinct City from Avail_Blood";
            
                ResultSet rs = st.executeQuery(queery);
                while(rs.next())
                {
                    CityRequestCombo1.addItem(rs.getString("City"));
                }
            
        }catch(Exception ex)
        {

        }
        finally
        {
            try
            {
                con.close();
            }catch(Exception ex)
            {

            }
        }
         
    }
         
    
    
    private void SearchTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SearchTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTableMouseClicked

    private void SearchCityButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchCityButtonActionPerformed

        con = DBSCon.dataBaseConnection();
           try
           {
               Statement st = con.createStatement();
                       String queery = "select BloodBank,City,BloodType,Location,Bottles,Date from Avail_Blood where City = '"+CityRequestCombo1.getSelectedItem()+"'";
                       ResultSet rs = st.executeQuery(queery);
                       SearchTable.setModel(DbUtils.resultSetToTableModel(rs));
           }catch(Exception ex)
           {
               
           }
   finally 
           {
           try
           {
               con.close();
           }catch(Exception ex)
           {
               
           }
           }
        
        
    }//GEN-LAST:event_SearchCityButtonActionPerformed

    private void SearchBloodButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBloodButtonActionPerformed
        con = DBSCon.dataBaseConnection();
           try
           {
               Statement st = con.createStatement();
                       String queery = "select BloodBank,City,BloodType,Location,Bottles,Date from Avail_Blood where BloodType = '"+CityRequestCombo2.getSelectedItem()+"'";
                       ResultSet rs = st.executeQuery(queery);
                       SearchTable.setModel(DbUtils.resultSetToTableModel(rs));
           }catch(Exception ex)
           {
               
           }
   finally 
           {
           try
           {
               con.close();
           }catch(Exception ex)
           {
               
           }
           }
    }//GEN-LAST:event_SearchBloodButtonActionPerformed

    private void SearchDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDateButtonActionPerformed
        
        con = DBSCon.dataBaseConnection();
           try
           {
               Statement st = con.createStatement();
                       String queery = "select BloodBank,City,BloodType,Location,Bottles,Date from Avail_Blood where Date = '"+CityRequestCombo3.getSelectedItem()+"'";
                       ResultSet rs = st.executeQuery(queery);
                       SearchTable.setModel(DbUtils.resultSetToTableModel(rs));
           }catch(Exception ex)
           {
               
           }
   finally 
           {
           try
           {
               con.close();
           }catch(Exception ex)
           {
               
           }
           }
        
    }//GEN-LAST:event_SearchDateButtonActionPerformed

    private void SearchBankButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBankButtonActionPerformed
        con = DBSCon.dataBaseConnection();
           try
           {
               Statement st = con.createStatement();
                       String queery = "select BloodBank,City,BloodType,Location,Bottles,Date from Avail_Blood where BloodBank = '"+CityRequestCombo4.getSelectedItem()+"'";
                       ResultSet rs = st.executeQuery(queery);
                       SearchTable.setModel(DbUtils.resultSetToTableModel(rs));
           }catch(Exception ex)
           {
               
           }
   finally 
           {
           try
           {
               con.close();
           }catch(Exception ex)
           {
               
           }
           }
    }//GEN-LAST:event_SearchBankButtonActionPerformed

    private void LogoutDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutDButtonActionPerformed
        dispose();
        new MainForm().show();
    }//GEN-LAST:event_LogoutDButtonActionPerformed

    private void IdRequesttxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdRequesttxtKeyPressed
        String IdRequest = IdRequesttxt.getText();
        int length = IdRequest.length();
        char c = evt.getKeyChar();
        
        if (evt.getKeyChar()>='0' && evt.getKeyChar()<='9')
        {
            if(length<5){
                IdRequesttxt.setEditable(true);
            }else
            {
                IdRequesttxt.setEditable(false);
            }
        }else
        {
            if(evt.getExtendedKeyCode()==KeyEvent.VK_BACKSPACE || evt.getExtendedKeyCode()==KeyEvent.VK_DELETE)
            {
                IdRequesttxt.setEditable(true);
            }else
            {
                IdRequesttxt.setEditable(false);
            }
        }
    }//GEN-LAST:event_IdRequesttxtKeyPressed

    private void NameRequesttxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NameRequesttxtKeyPressed
        char c = evt.getKeyChar();
        if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            NameRequesttxt.setEditable(true);
            
        }else{
            NameRequesttxt.setEditable(false);
        }
    }//GEN-LAST:event_NameRequesttxtKeyPressed

    private void LocationRequesttxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LocationRequesttxtKeyPressed
       char c = evt.getKeyChar();
        if (Character.isLetter(c)||Character.isWhitespace(c)||Character.isISOControl(c)){
            LocationRequesttxt.setEditable(true);
            
        }else{
            LocationRequesttxt.setEditable(false);
        }
    }//GEN-LAST:event_LocationRequesttxtKeyPressed

    public void showProfile()
   {
           con = DBSCon.dataBaseConnection();
           try
           {
               Statement st = con.createStatement();
                       String queery = "select * from User_Reg where id = '"+Integer.parseInt(MainForm.getID())+"'";
                       ResultSet rs = st.executeQuery(queery);
                       ProfileDTable.setModel(DbUtils.resultSetToTableModel(rs));
           }catch(Exception ex)
           {
               
           }
   finally 
           {
           try
           {
               con.close();
           }catch(Exception ex)
           {
               
           }
           }
                  
   }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Patient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AvailBloodDonorTable;
    private javax.swing.JComboBox BTypeRequestCombo;
    private javax.swing.JTextField BankRequesttxt;
    private javax.swing.JComboBox BottleRequestCombo;
    private javax.swing.JComboBox CityRequestCombo;
    private javax.swing.JComboBox CityRequestCombo1;
    private javax.swing.JComboBox CityRequestCombo2;
    private javax.swing.JComboBox CityRequestCombo3;
    private javax.swing.JComboBox CityRequestCombo4;
    private javax.swing.JTextField IdRequesttxt;
    private javax.swing.JTextField LocationRequesttxt;
    private javax.swing.JButton LogoutDButton;
    private javax.swing.JTextField NameRequesttxt;
    private javax.swing.JTable ProfileDTable;
    private javax.swing.JButton RDeleteButton;
    private javax.swing.JButton RInsertButton;
    private javax.swing.JButton RUpdateButton;
    private com.toedter.calendar.JDateChooser RequestDateChooser;
    private javax.swing.JButton SearchBankButton;
    private javax.swing.JButton SearchBloodButton;
    private javax.swing.JButton SearchCityButton;
    private javax.swing.JButton SearchDateButton;
    private javax.swing.JTable SearchTable;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables

      public void showSpecificBloodData(int id)
   {
           con = DBSCon.dataBaseConnection();
           try
           {
               Statement st = con.createStatement();
                       String queery = "select BloodBank,City,BloodType,Location,Bottles,Date from Request where Id = "+ id;
                       ResultSet rs = st.executeQuery(queery);
                       AvailBloodDonorTable.setModel(DbUtils.resultSetToTableModel(rs));
           }catch(Exception ex)
           {
               
           }
   finally 
           {
           try
           {
               con.close();
           }catch(Exception ex)
           {
               
           }
           }
           
           
   }
    
}
